# Имя рабочего процесса
name: Build and Push to DigitalOcean

# Триггер для запуска: пуш в ветку "master"
on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Вход в DigitalOcean Container Registry
      - name: Log in to DigitalOcean
        uses: docker/login-action@v3
        with:
          # Адрес вашего репозитория из секрета
          registry: ${{ secrets.DO_REGISTRY_URL }}
          # Логином является сам токен
          username: ${{ secrets.DO_PAT }}
          # Паролем также является токен
          password: ${{ secrets.DO_PAT }}

      # 3. Сборка и отправка Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Теги для образа с полным путем к репозиторию
          tags: |
            ${{ secrets.DO_REGISTRY_URL }}/hebrewtgbot:latest
            ${{ secrets.DO_REGISTRY_URL }}/hebrewtgbot:${{ github.sha }}
